name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production 
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Navegar al directorio del proyecto
          cd /var/www/laravel-admin
          
          # Hacer pull de los últimos cambios
          git pull origin master
          
          # Instalar dependencias de Composer
          composer install --no-dev --optimize-autoloader
          
          # Instalar dependencias de Node.js
          npm ci
          
          # Hacer build de Vite
          npm run build
          
          # Limpiar cache de Laravel
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          
          # Optimizar Laravel para producción
          php artisan optimize
          
          # Ejecutar migraciones si hay nuevas
          php artisan migrate --force
          
          # Cambiar permisos de storage y cache
          chmod -R 775 storage bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache
          
          # Reiniciar servicios si es necesario
          sudo systemctl reload nginx
          sudo systemctl reload php8.2-fpm
          
          echo "Deploy completado exitosamente!" 